server:
  port: 3001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kbgh
    username: root
    password: rhakdnjdy1!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true